### ISSUE TITLE
Version 10 Preparations

### ISSUE THREAD

**Issue by DarthBanjo** [DarthBanjo/starwarsd6-essentialcompanion-od6s#14]
The data structure is changing in Foundry Version 10. 

- Wait to see how od6s handles the changes
- See what work needs to be done for the essential companion to match those changes

**Comment by algnc** [comment]
The module seems to be working OK for me in V10.

**Comment by b-gre** [comment]
Meanwhile od6s has migrated to Foundry 10 :)
Would be awesome to have the companion available as well.

**Comment by DarthBanjo** [comment]
I've read these comments and will continue work on this project soon!

**Comment by sioc-de-narf** [comment]
od6s looks still ok
