### ISSUE TITLE
Request to use checklist content 

### ISSUE THREAD

**Issue by algnc** [DarthBanjo/starwarsd6-essentialcompanion-od6s#3]
I would like to use your SWD6 config checklist from your README in the README for my module https://github.com/algnc/od6s-star-wars

Let me know if that's OK please.

**Comment by DarthBanjo** [comment]
Yes! Of course! I got most of it from discussions on the Star Wars D6 Discord server.

**Comment by DarthBanjo** [comment]
Also, I made your module a prerequisite of the one I was building. Your sheets look good.
