### ISSUE TITLE
Adding Character Templates from the D6 Holocron

### ISSUE THREAD

**Issue by mcbobbo** [DarthBanjo/starwarsd6-essentialcompanion-od6s#7]
As it happens I have all the data from the holocron site in text format and could help you with the templates if you'd like.  I could try to figure out the foundry json myself or could just send over formatted data.  Let me know if you'd like the help.

We looked at playing this yesterday (May the 4th) but couldn't quite get it ready in time.  I did finally get it figured out, but the character sheet gave me serious fits.  Having these templates would have made getting started much quicker.

And again, I've done a lot of the work already from when we brought this data into Fantasy Grounds two years ago.

**Comment by DarthBanjo** [comment]
I won’t say no to help!
Let me look at this later today then I can reply further.

**Comment by DarthBanjo** [comment]
I've added a compendium to store "Character Template" Items in, and have created a sample template (the Holovid Celebrity) for you to use as a guide.

The file: modules/starwarsd6-essentialcompanion-od6s/packs/d6htemplates.db
I'll process all the WEG art for templates and store them in 200x200 .webp format in: modules/starwarsd6-essentialcompanion-od6s/art/items/templateArt

You're welcome to either fork the module, work on it on your own foundry system, and send a pull request when you're ready, or just send me the .db when you're ready and I'll make sure it works.

**Comment by mcbobbo** [comment]
I'm off to a good start:

```
Parsing Wroonian Captain
{'name': 'Wroonian Captain', 'agi': '9', 'per': '9', 'kno': '7', 'str': '9', 'mec': '14', 'tec': '6', 'Unmapped - heavy blaster pistol (5D)': '15'}
------------------------------
Parsing Xenoarchaeologist
{'name': 'Xenoarchaeologist', 'agi': '9', 'per': '10', 'kno': '12', 'str': '9', 'mec': '8', 'tec': '6', 'Unmapped - blaster pistol (4D)': '12'}
------------------------------
Parsing Young Jedi
{'name': 'Young Jedi', 'agi': '9', 'per': '12', 'kno': '6', 'str': '6', 'mec': '6', 'tec': '6', 'met': '3', 'Unmapped - Blaster Pistol (4D)': '12'}
------------------------------
Parsing Young Senatorial (Template)
{'name': 'Young Senatorial (Template)', 'agi': '9', 'per': '10', 'kno': '12', 'str': '9', 'mec': '8', 'tec': '6', 'Unmapped - hold-out blaster (3D)': '9'}
```

I think there's a way to reference other compendium entries for the unmapped things like equipment.  I'll have to look at that more.

How do the metaphysics and Force skills map?  The Young Jedi has three total D in them.  Should I add those together to get the 'met' score?  Or leave them one each?

**Comment by DarthBanjo** [comment]
Hm. I am looking at a template export that has the three force skills, I don't see a way to store individual values here. I would give the template a meta attribute value of 3. That gives an automatic 1D to all three force skills. 

The metaphysics rating acts like a hidden 7th attribute, with Control/Sense/Alter underneath it.

` "items": [
      {
        "name": "Control",
        "type": "skill",
        "description": "<p><span class=\"fontstyle0\">Control </span><span class=\"fontstyle2\">is the Jedi&rsquo;s ability to control her own body. A Jedi with </span><span class=\"fontstyle0\">control </span><span class=\"fontstyle2\">can access her own internal well of Force energy, learning harmony with and mastery over the functions of her own body</span> <br style=\"font-style: normal; font-variant: normal; font-weight: normal; letter-spacing: normal; line-height: normal; orphans: 2; text-align: -webkit-auto; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-size-adjust: auto; -webkit-text-stroke-width: 0px;\" /><br /></p>"
      },
      {
        "name": "Sense",
        "type": "skill",
        "description": "<p><span class=\"fontstyle0\">Sense </span><span class=\"fontstyle2\">teaches a Jedi to sense the Force in other things beyond her own body. The Jedi learns to feel the bonds that connect all living things and gains the ability to understand how all things are interconnected. </span><span class=\"fontstyle0\">Sense </span><span class=\"fontstyle2\">governs powers such as detecting danger and learning information about the world around the Jedi.</span><br style=\"font-style: normal; font-variant: normal; font-weight: normal; letter-spacing: normal; line-height: normal; orphans: 2; text-align: -webkit-auto; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-size-adjust: auto; -webkit-text-stroke-width: 0px;\" /><br /></p>"
      },
      {
        "name": "Alter",
        "type": "skill",
        "description": "<p><span class=\"fontstyle0\">A Jedi with </span><span class=\"fontstyle2\">alter </span><span class=\"fontstyle0\">learns how to change the distribution and nature of the Force. Jedi who have mastered </span><span class=\"fontstyle2\">alter </span><span class=\"fontstyle0\">can move physical objects with their minds, can help others control their own Force, or can manipulate the Force in the bodies of others. This power can be used to change the perceptions of others and make them come to incorrect conclusions.</span> <br style=\"font-style: normal; font-variant: normal; font-weight: normal; letter-spacing: normal; line-height: normal; orphans: 2; text-align: -webkit-auto; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-size-adjust: auto; -webkit-text-stroke-width: 0px;\" /><br /></p>"
      }
    ],`

**Comment by mcbobbo** [comment]
[d6htemplates.db.txt](https://github.com/DarthBanjo/starwarsd6-essentialcompanion-od6s/files/8655362/d6htemplates.db.txt)

Okay, here's what I could figure out.  No items/equipment yet, but all the stats and the raw text from the website is in for each character type.

**Comment by DarthBanjo** [comment]
This looks very promising and a huge step forward. I can look at it tomorrow.

**Comment by DarthBanjo** [comment]
This is great work. I've finished working on the images for all the templates, and can assign the issue to me to finish.

**Comment by DarthBanjo** [comment]
I'll attribute you on the readme, is @mcbobbo fine?

**Comment by DarthBanjo** [comment]
I'm working on this, just slowly. I solved an issue with skills and item storage and will slowly work my way through the templates as time allows.

**Comment by DarthBanjo** [comment]
Finished 184 templates, updating release soon.

**Comment by mcbobbo** [comment]
Yes that works for me, thank you.
